#update system before installing anything

sudo apt update && apt upgrade -y

# 1 install apache 

sudo systemctl status apache2
sudo apt install apache2 

sudo systemctl status apache2


#Step 2 install php 
sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install php8.2 -y
sudo apt-get install -y php8.2-cli php8.2-common php8.2-fpm php8.2-mysql php8.2-zip php8.2-gd php8.2-mbstring php8.2-curl php8.2-xml php8.2-bcmath




sudo nano /var/www/html/test.php
<?php
phpinfo();
?>



#setp 3 Download and Install a Database Manager
sudo apt install php8.2-sqlite3



sudo apt install mariadb-server 
sudo mysql_secure_installation
Remove anonymous users? [Y/n] y
Disallow root login remotely? [Y/n] n
Remove test database and access to it? [Y/n] y
Reload privilege tables now? [Y/n] y


#step 4 install composer 


sudo curl -sS https://getcomposer.org/installer | php


sudo mv composer.phar /usr/local/bin/composer

sudo chmod +x /usr/local/bin/composer



#setup project with git 


sudo chgrp -R www-data /var/www/html/poem_club/
sudo chmod -R 775 /var/www/html/poem_club/storage
sudo chmod -R 775 database




cd /etc/apache2/sites-available
sudo nano poem.conf



<VirtualHost *:80>
   ServerName thedomain.com
   ServerAdmin webmaster@thedomain.com
   DocumentRoot /var/www/html/poem_club/public

   <Directory /var/www/html/poem_club>
       AllowOverride All
   </Directory>
   ErrorLog ${APACHE_LOG_DIR}/error.log
   CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>




sudo a2dissite 000-default.conf
sudo a2ensite poem
sudo a2enmod rewrite
sudo systemctl restart apache2


